---
version: '3.7'
services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - 8514:8514
    environment:
      - MYSQL_ROOT_PASSWORD=qwe123rty
      - MYSQL_DATABASE=dd
      - MYSQL_USER=acp4pogynvaeidfj
      - MYSQL_PASSWORD=jc31d2qyy7h9jv5jn1u9uosjksxzaizw
  maven_custom:
    build: 
      context: ./maven_custom
      dockerfile: Dockerfile
    volumes:
      - data2:/tmp/target/
    depends_on:
      - mysql_db
  tomcat:
    image: tomcat:9.0.71-jdk11-temurin-focal
    volumes: 
       - type: volume
         source: data2
         target: /usr/local/tomcat/webapps/
         volume:
           nocopy: true
    ports:
      - 8080:8080
    depends_on:
      - maven_custom
      - mysql_db
volumes:
  data2: